[clone : clone] + '[' false '=' true ]
[clone : clone] + '[' false '=' true ]
[clone : clone] + '[' false '=' true ]
[clone : clone] + CHECKOUT_DIR=/workspace/output/
[clone : clone] + '[' true '=' true ]
[clone : clone] + cleandir
[clone : clone] + '[' -d /workspace/output/ ]
[clone : clone] + rm -rf '/workspace/output//*'
[clone : clone] + rm -rf /workspace/output//.git
[clone : clone] + rm -rf '/workspace/output//..?*'
[clone : clone] + test -z 
[clone : clone] + test -z 
[clone : clone] + test -z 
[clone : clone] + git config --global --add safe.directory /workspace/output
[clone : clone] + /ko-app/git-init '-url=https://github.com/zidanakqa/devops-capstone-project.git' '-revision=main' '-refspec=' '-path=/workspace/output/' '-sslVerify=true' '-submodules=true' '-depth=1' '-sparseCheckoutDirectories='
[clone : clone] {"level":"info","ts":1754040720.708259,"caller":"git/git.go:176","msg":"Successfully cloned https://github.com/zidanakqa/devops-capstone-project.git @ 58be79f5f9350b13295c1cea5c62b12a3c545715 (grafted, HEAD, origin/main) in path /workspace/output/"}
[clone : clone] {"level":"info","ts":1754040721.3898134,"caller":"git/git.go:215","msg":"Successfully initialized and updated submodules in path /workspace/output/"}
[clone : clone] + cd /workspace/output/
[clone : clone] + git rev-parse HEAD
[clone : clone] + RESULT_SHA=58be79f5f9350b13295c1cea5c62b12a3c545715
[clone : clone] + EXIT_CODE=0
[clone : clone] + '[' 0 '!=' 0 ]
[clone : clone] + git log -1 '--pretty=%ct'
[clone : clone] + RESULT_COMMITTER_DATE=1753888180
[clone : clone] + printf '%s' 1753888180
[clone : clone] + printf '%s' 58be79f5f9350b13295c1cea5c62b12a3c545715
[clone : clone] + printf '%s' https://github.com/zidanakqa/devops-capstone-project.git

[lint : flake8] ***** Installing flake8 *****
[lint : flake8] Requirement already satisfied: pip in /usr/local/lib/python3.9/site-packages (23.0.1)
[lint : flake8] Collecting pip
[lint : flake8]   Downloading pip-25.2-py3-none-any.whl (1.8 MB)
[lint : flake8]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 30.2 MB/s eta 0:00:00
[lint : flake8] Installing collected packages: pip
[lint : flake8]   Attempting uninstall: pip
[lint : flake8]     Found existing installation: pip 23.0.1
[lint : flake8]     Uninstalling pip-23.0.1:
[lint : flake8]       Successfully uninstalled pip-23.0.1
[lint : flake8] Successfully installed pip-25.2
[lint : flake8] WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[lint : flake8] Collecting flake8
[lint : flake8]   Downloading flake8-7.3.0-py2.py3-none-any.whl.metadata (3.8 kB)
[lint : flake8] Collecting mccabe<0.8.0,>=0.7.0 (from flake8)
[lint : flake8]   Downloading mccabe-0.7.0-py2.py3-none-any.whl.metadata (5.0 kB)
[lint : flake8] Collecting pycodestyle<2.15.0,>=2.14.0 (from flake8)
[lint : flake8]   Downloading pycodestyle-2.14.0-py2.py3-none-any.whl.metadata (4.5 kB)
[lint : flake8] Collecting pyflakes<3.5.0,>=3.4.0 (from flake8)
[lint : flake8]   Downloading pyflakes-3.4.0-py2.py3-none-any.whl.metadata (3.5 kB)
[lint : flake8] Downloading flake8-7.3.0-py2.py3-none-any.whl (57 kB)
[lint : flake8] Downloading mccabe-0.7.0-py2.py3-none-any.whl (7.3 kB)
[lint : flake8] Downloading pycodestyle-2.14.0-py2.py3-none-any.whl (31 kB)
[lint : flake8] Downloading pyflakes-3.4.0-py2.py3-none-any.whl (63 kB)
[lint : flake8] Installing collected packages: pyflakes, pycodestyle, mccabe, flake8
[lint : flake8] 
[lint : flake8] Successfully installed flake8-7.3.0 mccabe-0.7.0 pycodestyle-2.14.0 pyflakes-3.4.0
[lint : flake8] WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
[lint : flake8] ***** Running flake8 *****
[lint : flake8] 0

[tests : nosetests] ***** Installing dependencies *****
[tests : nosetests] Requirement already satisfied: pip in /usr/local/lib/python3.9/site-packages (23.0.1)
[tests : nosetests] Collecting pip
[tests : nosetests]   Downloading pip-25.2-py3-none-any.whl (1.8 MB)
[tests : nosetests]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 72.4 MB/s eta 0:00:00
[tests : nosetests] Requirement already satisfied: wheel in /usr/local/lib/python3.9/site-packages (0.44.0)
[tests : nosetests] Collecting wheel
[tests : nosetests]   Downloading wheel-0.45.1-py3-none-any.whl (72 kB)
[tests : nosetests]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.5/72.5 kB 35.4 MB/s eta 0:00:00
[tests : nosetests] Installing collected packages: wheel, pip
[tests : nosetests]   Attempting uninstall: wheel
[tests : nosetests]     Found existing installation: wheel 0.44.0
[tests : nosetests]     Uninstalling wheel-0.44.0:
[tests : nosetests]       Successfully uninstalled wheel-0.44.0
[tests : nosetests]   Attempting uninstall: pip
[tests : nosetests]     Found existing installation: pip 23.0.1
[tests : nosetests]     Uninstalling pip-23.0.1:
[tests : nosetests]       Successfully uninstalled pip-23.0.1
[tests : nosetests] Successfully installed pip-25.2 wheel-0.45.1
[tests : nosetests] WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[tests : nosetests] WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
[tests : nosetests] ***** Running nosetests with: -v --with-spec --spec-color
[tests : nosetests] nose.config: INFO: Ignoring files matching ['^\\.', '^_', '^setup\\.py$']
[tests : nosetests] nose.plugins.cover: INFO: Coverage report will include only packages: ['service']
[tests : nosetests] 
[tests : nosetests] Test Flask CLI Commands
[tests : nosetests] [1;32m- It should call the db-create command[1;0m
[tests : nosetests] 
[tests : nosetests] Test Cases for Account Model
[tests : nosetests] [1;32m- It should Create an account and add it to the database[1;0m
[tests : nosetests] [1;32m- It should Create an Account and assert that it exists[1;0m
[tests : nosetests] [1;32m- It should Delete an account from the database[1;0m
[tests : nosetests] [1;32m- It should Deserialize an account[1;0m
[tests : nosetests] [1;32m- It should not Deserialize an account with a KeyError[1;0m
[tests : nosetests] [1;32m- It should not Deserialize an account with a TypeError[1;0m
[tests : nosetests] [1;32m- It should Find an Account by name[1;0m
[tests : nosetests] [1;32m- It should List all Accounts in the database[1;0m
[tests : nosetests] [1;32m- It should Read an account[1;0m
[tests : nosetests] [1;32m- It should Serialize an account[1;0m
[tests : nosetests] [1;32m- It should Update an account[1;0m
[tests : nosetests] 
[tests : nosetests] Account Service Tests
[tests : nosetests] [1;32m- It should not Create an Account when sending the wrong data[1;0m
[tests : nosetests] [1;31m- It should return a CORS header (ERROR)[1;0m
[tests : nosetests] [1;32m- It should Create a new Account[1;0m
[tests : nosetests] [1;32m- It should Delete an Account[1;0m
[tests : nosetests] [1;32m- It should Read a single Account[1;0m
[tests : nosetests] [1;32m- It should Get a list of Accounts[1;0m
[tests : nosetests] [1;32m- It should not Read an Account that is not found[1;0m
[tests : nosetests] [1;32m- It should be healthy[1;0m
[tests : nosetests] [1;32m- It should get 200_OK from the Home Page[1;0m
[tests : nosetests] [1;32m- It should not allow an illegal method call[1;0m
[tests : nosetests] [1;32m- It should not Create an Account when sending the wrong media type[1;0m
[tests : nosetests] [1;32m- It should Update an existing Account[1;0m
[tests : nosetests] [1;32m- It should not Update an Account that is not found[1;0m
[tests : nosetests] 
[tests : nosetests] ======================================================================
[tests : nosetests] ERROR: It should return a CORS header
[tests : nosetests] ----------------------------------------------------------------------
[tests : nosetests] Traceback (most recent call last):
[tests : nosetests]   File "/workspace/source/tests/test_routes.py", line 200, in test_cors_security
[tests : nosetests]     response = self.client.get('/', environ_overrides=self.HTTPS_ENVIRON)
[tests : nosetests] AttributeError: 'TestAccountService' object has no attribute 'HTTPS_ENVIRON'
[tests : nosetests] 
[tests : nosetests] Name                               Stmts   Miss  Cover   Missing
[tests : nosetests] ----------------------------------------------------------------
[tests : nosetests] service/__init__.py                   22      3    86%   40-43
[tests : nosetests] service/common/__init__.py             0      0   100%
[tests : nosetests] service/common/cli_commands.py         7      0   100%
[tests : nosetests] service/common/error_handlers.py      32      3    91%   76-78
[tests : nosetests] service/common/log_handlers.py        10      1    90%   21
[tests : nosetests] service/common/status.py              46      0   100%
[tests : nosetests] service/config.py                     11      5    55%   12-16
[tests : nosetests] service/models.py                     69      3    96%   32, 98, 127
[tests : nosetests] service/routes.py                     57      0   100%
[tests : nosetests] ----------------------------------------------------------------
[tests : nosetests] TOTAL                                254     15    94%
[tests : nosetests] ----------------------------------------------------------------------
[tests : nosetests] Ran 25 tests in 22.259s
[tests : nosetests] 
[tests : nosetests] FAILED (errors=1)
[tests : nosetests] 

